print(123456)
#raise ValueError('Levantei um erro')  # Forma de for√ßar o levantamento de um erro
print(789)
